### ISSUE TITLE
Remove ./dist/ folder from repo

### ISSUE THREAD

**Issue by acabal** [hisaac/christopher-morley_parnassus-on-wheels#1]
The repo should not contain build versions of its own source

**Comment by hisaac** [comment]
This is now fixed by commits 41e44829ea00ce5fc60d7a0bc4456c1ee301983e and 547927312bc3c1ee582986087d7ab7e0698b917b.

**Comment by acabal** [comment]
I see you removed it by adding a `.gitignore` file, which is also illegal. Can you remove the `.gitignore` file?

Running the `lint` tool will catch these kinds of problems for you, before you commit.

**Comment by hisaac** [comment]
Yep, I can do that. And good tip on running `lint` before each commit.

How come gitignores are illegal?

**Comment by acabal** [comment]
Because each person has their own flavor of `.gitignore`, and they're not part of the ebook source. Since you shouldn't be building inside the source directory there's basically no need for one anyway.

**Comment by hisaac** [comment]
Ok, that makes sense.

It may be good to call that out in the [step-by-step guide](https://standardebooks.org/contribute/producing-an-ebook-step-by-step) to provide some more clarity. Step 20 is where it first talks about building, and based on the shell commands there, it looks like it’s just building into the root directory of the project.

**Comment by acabal** [comment]
OK, I've updated the guide to be clearer.
