### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [hisaac/christopher-morley_parnassus-on-wheels#3]
- Remove cc: namespace from the `<package>` element. (This was probably removed in the template after you had already started production.)
- http://standardebooks.org namespace must be https across entire project. This can be a simple project-wide find and replace.
- long-description must be escaped HTML. I see the book title is not italicized in there either. See the metadata manual: https://standardebooks.org/contribute/metadata

**Comment by hisaac** [comment]
I believe this is fixed now, in commit b16617fa619e1b43ae7711c17a8d2b69d1bbc664. Does the long-description look better to you?

**Comment by acabal** [comment]
Looks good, with the minor nit of please move the comma inside the quotation marks in `“Mount Parnassus”,`. Thanks :)
