### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by acabal** [hisaac/christopher-morley_parnassus-on-wheels#4]
- I see you have a hymn in there. Instead of using a class, this should be targeted with z3998 semantics. z3998 has both the "song" and "hymn" keyword, you can use either one as appropriate. Then, remove the class and target using the `epub:type` attribute.
- The hymn header should be in a `<header>` element. Remove the class and target it with specific CSS, for example: `[epub|type~="z3998:hymn"] header p`.
- You can remove the `governers-calling-card-location` class, I don't know why that's styled with a 1em text indent. In that same block, "Raleigh Stone Stafford" is not a signature, it's just the guy's name. So you can target that with a more clever selector like `.governers-calling-card p:first-child` and drop the class entirely.
-The `calling-card-signoff` class seems to be unused, please remove it.
- Remove the `p[epub|type~="z3998:song"] span:nth-child(even)` selector; this is not only too complex for most ereaders but it's not in our standard. Instead use the "i1" class and selector to indent each specific line, per our standard.
- I see there's a journal excerpt styled in all italics. I would prefer to remove the italics here, since the margin on the `<blockquote>` element is enough visual signal to the reader to indicate that we're reading a quotation. So you can remove that class and the associated styling.
- Remove `<hr/>` from the `newspaper-clipping` section. The semantics of `<hr/>` are "scene break" and it should not be used if all you want is a dividing line for visual presentation. Instead you can style it something like this: `.newspaper-clipping p + p{ border-top-width: 1px }`. (Note that we don't assign a color, so that reading systems can pick a color for night mode.)
- In `chapter-12.xhtml`, `<li>` items must have a direct block-level descendent like `<p>`, per our semantics manual. Make sure to do that for any other `<li>` elements there might be in the book.
- In `chapter-1.xhtml` the `book-title` class should be in a `<blockquote>` element, and make sure to indent the line following a `<br/>` to the same indentation level.
- In letters, the first line following a salutation should not be indented. You can add a style to catch all those.
- In `chapter-1.xhtml`, in the first letter, `<p>Believe us, ...` should be in the `<footer>` element. `<p>Believe us, ` is the valediction, not the `<footer>` is not the valediction. A valediction is the line like "Sincerely," which is usually followed by a signature. Double check any other letters in the book to make sure to catch issues like these.

**Comment by acabal** [comment]
- In `chapter-5.xhtml` the song is missing the required `<br/>` elements per our poetry/verse styling.

**Comment by acabal** [comment]
- Pretty much all books that are styled with `<i>` are missing the `epub:type="se:name.publication.book" semantic. For all cases in which an unsemantic `<i>` is used, an additional `epub:type` attribute must indicate what the `<i>` represents. The only exception are italics for sounds to be read as sounds (like bzzzzz).

**Comment by hisaac** [comment]
Good catches! I'm impressed by your ability to catch this stuff.

This one will take me a little longer to close, but I'll let you know when I do.

**Comment by hisaac** [comment]
Alright, I've made changes to resolve all of these. Let me know if you see anything else.

**Comment by acabal** [comment]
Great, I've gone ahead and released the ebook. Thanks for all your hard work!
